Kotlin/kotlinx-atomicfu

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
Fixes #25 
The [problem](https://github.com/Kotlin/kotlinx.atomicfu/pull/28#issuecomment-425624576) was that kotlinx-atomicfu module was not passed during local JS testing.
=> Some fragilities of JS transformer fixed (+ fixed JS local testing)

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
=> Inlining of atomic operations fixed

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
=> Skip changing source path for unprocessed native output

atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/LockFreedomTestEnvironment.kt
Threads that have terminated should be considered to make progress
=> Fixed shutdown sequence of LockFreedomTestEnvironment

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/ArrayElementInlineFuncTest.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/AtomicArrayTest.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/VolatileOnlyTest.kt
Inline functions on array elements fixed
=> array-element-inline-func

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/BaseKotlinGradleTest.kt, atomicfu-native/build.gradle, atomicfu/build.gradle, build.gradle, gradle.properties, gradle/publish-bintray.gradle, gradle/publish-npm-js.gradle, gradle/wrapper/gradle-wrapper.properties
* Gradle metadata format version 1.0 (stable)
* Using Gradle publish task for publishing
=> Gradle version 5.6.1

atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/LockFreedomTestEnvironment.kt
Prints stack-trace of a thread that fails to shutdown.
=> Better diagnostics when LockFreedomTestEnvironment fails to shutdown

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
The fix was mistakenly only applied to multiplatform projects. Extend it to
single-platform projects as well. Also, fix the compiler argument for the JS
compiler, which accepts -Xfriend-modules, not -Xfriend-paths.
=> Extend the fix from f404e552 to single-platform projects

atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/Synchronized.kt
=> Minor refactoring in MutexPool code

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt, atomicfu/build.gradle, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/ReentrantLockFieldTest.kt, gradle/node-js.gradle
=> Erasing reentrantLock fixed

README.md, atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
=> Multi-threaded version for Kotlin/Native

gradle.properties
=> ASM 7.2 for Java 11+ support

atomicfu/build.gradle
Fix IDEA build: fix setting native compilations
=> Fix native targets build in idea

atomicfu/build.gradle, gradle.properties, gradle/node-js.gradle, gradle/publish-bintray.gradle, gradle/test-mocha-js.gradle
Use new K/JS Gradle plugin for tests and publishing
Migrate to built-in node.js and Chrome test runners
=> Enable JS IR backend

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
This fixes the cases when an HMPP project is built with atomicfu, and its shared-native source set is published with an atomicfu 'depends' entry in the manifest but without a proper transitive dependency on atomicfu. This leads to such an artifact not being usable as a dependency in other projects with shared-native source sets, as the Kotlin/Native compiler will reject it because of a missing transitive dependency.
=> Add atomicfu dependency to all shared-native source sets

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/AtomicFU.common.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/AtomicArrayTest.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TopLevelTest.kt
=> Atomic*Array.size method introduced

README.md, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AsmUtil.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/AtomicFU.common.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/DelegatedPropertiesTest.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/SetArrayElementTest.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TraceTestCommon.kt, atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/AtomicFU.kt, atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/AtomicFU.kt, atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/AtomicfuBytecodeTest.kt, atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
```
private val _a = atomic(42)
var a: Int by _a
```
=> Delegated properties JVM

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AsmUtil.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/NestedAtomicFieldLoads.kt
=> Skipped transformation of the nested atomic field loads

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt, atomicfu/build.gradle, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/AtomicFU.common.kt, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/MangledJsNames.kt, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/Trace.common.kt, atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/TraceFormat.kt, atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TraceTestCommon.kt, atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/AtomicFU.kt, atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/Trace.kt, atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt, atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/Trace.kt, atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/AtomicfuReferenceJsTest.kt, atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/TraceToStringTest.kt
=> Debug trace enhancements

gradle.properties
=> ASM 9.1 for Java 15+ support

atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
=> Update the minimal ASM api version to ASM7

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
=> Сonfiguration cache bug caused by capturing the compilation object into lambda.

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
=> `kotlinx-atomicfu-runtime` transitive dependency

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
Fix for [KT-54167](https://youtrack.jetbrains.com/issue/KT-54167)
=> Pass friendPaths via BaseKotlinCompile$friendPath

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
Support for KGP < 1.7.0
Previous fix #247
=> Backward compatibility for adding the friendPaths

atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/internal/TestDsl.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/BaseKotlinGradleTest.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/JsProjectTest.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/JvmProjectTest.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/MppProjectTest.kt, atomicfu-gradle-plugin/src/test/resources/projects/jvm-simple/gradle.properties, atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/gradle.properties_both, atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/gradle.properties_js, atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/gradle.properties_jvm
Added tests for `atomicfu-gradle-plugin` with application of compiler IR transformation:
- Only JVM IR transformation
- Only JS IR transformation 
- Both JVM and JS IR transformations
=> More tests for atomicfu-gradle-plugin

README.md, atomicfu/build.gradle
=> Support all official K/N targets

atomicfu-gradle-plugin/build.gradle, gradle/compile-options.gradle
atomicfu-gradle-plugin should be compatible with the Kotlin version provided in Gradle.
=> Set apiVersion and languageVersion back to 1.4

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/JvmProjectTest.kt, atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/MppProjectTest.kt
=> Do not rename original destination directory of the compile task.

atomicfu/build.gradle, build.gradle
=> clean task can't delete the expanded.lock file on Windows

atomicfu/src/nativeInterop/cinterop/interop.def, atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/PosixLockSupport.kt, atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
* Confine all interop signatures into NativeMutexNode to simplify further working and maintenance
* Get rid of mutex_node_t
=> Tidy up our synchronization code (#413)

atomicfu-transformer/build.gradle.kts, atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/MetadataTransformer.kt, gradle/libs.versions.toml
=> Update kotlin-metadata to 2.0.0

build.gradle.kts, settings.gradle.kts
Since 1.9.24 and 2.0.0 there is no necessity to set dev version
=> Remove dev version of nodejs

build-settings-logic/src/main/kotlin/atomicfu-gradle-build-scan.settings.gradle.kts
This way we can use the Develocity token to authenticate on CI automatically
=> Set server on develocity extension

atomicfu/build.gradle.kts
=> Support deprecated linuxArm32Hfp target.

atomicfu-maven-plugin/build.gradle.kts
=> Added a release version as input for pom file generation.

integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/JvmVersionCompatibilityTest.kt
=> Skip JvmVersionCompatibilityTest

integration-testing/examples/multi-module-test/consumer/build.gradle.kts
This change is needed for `kotlin-community/dev` branch.
=> Fix kmp application plugin incompatibility

atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
=> Replaced internal defaultDestinationDirectory with destinationDirectory

gradle/wrapper/gradle-wrapper.properties
=> Use cache redirector to download Gradle

README.md, atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt, buildSrc/src/main/kotlin/gradle-compatibility.gradle.kts, gradle/libs.versions.toml, integration-testing/examples/jdk-compatibility/gradle.properties, integration-testing/examples/jvm-sample/gradle.properties, integration-testing/examples/mpp-sample/gradle.properties, integration-testing/examples/mpp-version-catalog/gradle/libs.versions.toml, integration-testing/examples/multi-module-test/gradle.properties, integration-testing/examples/plugin-order-bug/gradle.properties, integration-testing/examples/user-project/gradle.properties
=> Update Kotlin version to 2.2.0
