Kotlin/kotlinx-atomicfu

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/VolatileOnlyTest.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/VolatileOnlyBytecodeTest.kt
Atomic fields that use getValue/setValue are compiled down to the plain
volatile fields without FieldUpdater/VarHandle attached to them, so
that all @Volatile field in the source can be replaced with atomics
without loosing efficiency of the resulting bytecode.
In order to figure this out, method transformer is run in the Phase 2
on analysis in the special mode, so that data flow can be tracked
from fields to their method to see what methods are called on each
fields.
> Optimize volatile-only fields in JVM

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/UncheckedCastTest.kt
AtomicRef val is never null, so for JVM I can rely that nonnull check may be inserted by the compiler only and check for `dup, nonnull` pattern and then erase all instructions of null branch.
For JS unchecked casts like `(Kotlin.isType(tmp$_0 = atomicField, AtomicRef)` are erased and replaced with just `atomicField`
> Unchecked casts erased

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
The Kotlin Gradle plugin 1.3.60 has changed how friend paths are determined for the test compilations.
Earlier versions used to take the main's compile task destinationDir as the friend paths, but in 1.3.60,
there's a new mechanism that work on compilation level. According to it, the test compilation considers
the main's output.classesDirs as its friend paths.
The atomicfu-gradle-plugin modifies both the main compilation's output.classesDirs
and the test compilation's classpath, so that they point to different locations.
This caused internal visibility issues with Kotlin 1.3.60.
To fix this, add the main's original classesDirs to the test freeCompilerArgs
as -Xfriend-paths to ensure that internals are visible in the main's original
classes.
> Add the original classesDirs to the friend paths of test compilations

- README.md
I saw there was lock free stuff ❤️ but sadly the links were broken 😢 thus fix them!
[Current/Before README.md](https://github.com/Kotlin/kotlinx.atomicfu/blob/master/README.md#testing-lock-free-data-structures-on-jvm) links under
[New/After README.md](https://github.com/3ygun/kotlinx.atomicfu/blob/drs-readme-lockfree-links/README.md#testing-lock-free-data-structures-on-jvm) links under
> Update README.md's LockFree on JVM links

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/MetadataTransformer.kt
- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/AtomicFU.common.kt
- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/locks/Synchronized.common.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/ReentrantLockTest.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/InlineCASTest.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/LockTest.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TopLevelTest.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/UncheckedCastTest.kt
- atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/AtomicfuBytecodeTest.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/ByteUtil.kt
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- atomicfu/src/nativeTest/kotlin/kotlinx/atomicfu/locks/SynchronizedTest.kt
- gradle.properties
`ReentrantLock` added
JVM: typealias on `juc.locks.ReentrantLock`
JS: no-op lock
Native: implementation with `LockState`
> ReentrantLock support added

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
The original implementation assumed the system-dependent path separator, while the Kotlin compiler
actually splits the argument using just commas. This affected only projects which had more than one 
entry in the original classes dirs, such as projects using Kapt (it has an additional output classes directory).
This change, in particular, fixes the issue https://youtrack.jetbrains.com/issue/KT-35942
> Fix the friend paths compiler args separator

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TopLevelStoredToLocalVariableTest.kt
For a static field stored to local: in the transformed bytecode the local variable is removed and load instructions are replaced with `getstatic` insn of the corresponding field.  
\+ small fix in the JS transformer to match the name-format of generated local variables `$receiver_i`
Fixes #118
> Fixed storing top-level atomics to local variables.

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu/build.gradle
- atomicfu/src/commonTest/kotlin/bytecode_test/NoAccessPrivateTopLevelReflectionTest.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/PackagePrivateTopLevelReflectionTest.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/PrivateFieldAccessFromInnerClassReflectonTest.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/PrivateTopLevelReflectionTest.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/PublicTopLevelReflectionTest.kt
- atomicfu/src/commonTest/kotlin/internal_test1/B.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/TopLevelTest.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/MetadataReflectionTest.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/ReflectionTestBase.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/SyntheticFUFieldsTest.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/TopLevelGeneratedDeclarationsReflectionTest.kt
Access modifiers fixed for: 
- `*RefVolatile` classes
- volatile primitive type fields inside `*RefVolatle` classes
- synthetic `FU` and `*RefVolatile` fields
> Access modifiers and naming of *RefVolatile classes fixed.

- atomicfu-gradle-plugin/build.gradle
- atomicfu-gradle-plugin/src/test/resources/projects/jvm-simple/build.gradle
- atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/build.gradle
- atomicfu/build.gradle
- build.gradle
- gradle/compile-options.gradle
To be used in specific kotlinx-train CI configuration. It's needed for faster adoption of JVM IR compiler.
> Add build parameter to build atomicfu with JVM IR compiler

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
Currently, the transformer only catches exceptions while errors like `ClassNotFoundError` are not handled properly. This leads to a poor diagnostic because it's not possible to narrow down what file wasn't processed and why.
> Make transformer catch and report all error types

- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/AtomicFU.common.kt
- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/Trace.common.kt
- atomicfu/src/jsMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
- atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
The `Trace` parameter with a default value, added to atomic factory functions, broke binary compatibility in`0.15.0` 
For now, the fix is to return old declarations of atomic factory functions with one parameter.
> Binary compatibility

- atomicfu/build.gradle
There was a problem with running tests excluded in `transformedTest*` tasks in Idea.
The following error was thrown:
```
No tests found for given includes: [**/*LFTest.*](exclude rules) [kotlinx.atomicfu.test.LockFreeQueueLFTest](filter.includeTestsMatching)
```
while these tests were executed correctly in the terminal.
Seems that Idea sets the property `failOnNoMatchingTests` to true in it's init script. 
Setting this property to false in gradle has priority over the Idea settings and solves the problem.
> Fixed running excluded tests in Idea

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/Trace.common.kt
JS transformer is fixed to remove the reference to `kotlinx.atomicfu.TraceBase` class
> Removing reference to TraceBase class from JS

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/SplitLvt.kt
- atomicfu/src/jvmTest/kotlin/kotlinx/atomicfu/test/AtomicfuBytecodeTest.kt
The compiler splits LVT in coroutines and thus we need to update all the
split records.
#KT-47749
> Update all split LVT instead of only one record

- README.md
It looks like the artifact name specified in the `README` under [the section](https://github.com/Kotlin/kotlinx.atomicfu#common) on how to include in `common` sourcesets is incorrect, has somewhat recently changed, or something failed to properly publish to Maven Central.
When I attempt to include `org.jetbrains.kotlinx:atomicfu-common:0.16.3` as a dependency in common code, resolution fails - but when I include `org.jetbrains.kotlinx:atomicfu:0.16.3`, resolution succeeds.
> Correct artifact name for instructions on use within common sourceset.

- README.md
The maven example in the README currently has  `variant` as a configuration property of the `kotlin-maven-plugin`, but it actually belongs to the `atomicfu-maven-plugin`.
> Move variant property to the correct maven plugin in the README

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/JsProjectTest.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/MppProjectTest.kt
`org.jetbrains.kotlin.js` plugin does not use the infrastructure of the gradle java-plugin anymore (specifically java sourceSets), so transformation config for Kotlin/JS projects was fixed. 
Now `js` and `multiplatform` projects share configuration of target compilations.
> Support of Kotlin/JS projects in AtomicfuGradlePlugin

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AsmUtil.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformerJS.kt
- atomicfu/src/commonTest/kotlin/kotlinx/atomicfu/test/DelegatedPropertiesTest.kt
* Js transformer: checking owner class of the delegated fields
* JVM transformer: does not rely on the generated name of the field delegate
* Top-level delegated properties for JVM and JS
Fixes #83
> Bug fixes for delegated fields support

- README.md
According to the official's [document](https://kotlinlang.org/docs/migrating-multiplatform-project-to-14.html#follow-the-default-libraries-layout), platform suffix for MPP library name is not recommended, also it doesn't exist in the maven central.
> Update README.md: Fix dependency for common module

- README.md
- atomicfu-gradle-plugin/build.gradle
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- atomicfu-maven-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/TransformMojo.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- Added support of the compiler plugin transformation to the `AtomicfuGradlePlugin`.
- `atomicfu-gradle-plugin` test projects are ignored for a while. I'm going to create a PR with new test projects soon.
- Kotlin version is for now `1.7.0-dev-565`, [built](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_DeployMavenArtifacts/160253827?showRootCauses=false&expandBuildChangesSection=true) from the `1.6.20-M1-release branch`
> Atomicfu Js/Ir compiler plugin supported in the gradle plugin

- gradle.properties
We need new metadata to update `languageVersion` to 1.8
Revealed by [failing tests](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_atomicfu/212226612?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildProblemsSection=true) in `kotlinx.train-1.8.0` branch.
> Update kotlinx.metadata to 0.5.0

- build.gradle
- buildSrc/build.gradle.kts
Removed old references to Bintray, that caused the resolution failure.
[Here](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_BuildPlayground_MilkyWayMargaritaBobova_atomicfu/228941213?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true) is the green build, after replacement
> Replaced jcenter with mavenCentral

- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/JsProjectTest.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/MppProjectTest.kt
- atomicfu-gradle-plugin/src/test/resources/projects/js-simple/gradle.properties_js_legacy
- atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/gradle.properties_js_legacy
- atomicfu-gradle-plugin/src/test/resources/projects/mpp-simple/gradle.properties_jvm
- gradle.properties
Plus explicit specification of Kotlin JS legacy backend in `atomicfu-gradle-plugin` tests, as it was deprecated in 1.8.0.
> Update Kotlin to 1.8.0

- atomicfu-gradle-plugin/build.gradle
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- Pass compiler plugin dependency `atomicfu` in AtomicfuGradlePlugin
- Always pass `kotlinx-atomicfu-runtime` dependency
Fixes https://youtrack.jetbrains.com/issue/KT-57235
> Fix compiler plugin dependency in AtomicfuGradlePlugin

- atomicfu/build.gradle
Related YT issue: https://youtrack.jetbrains.com/issue/KT-53748/Remove-KotlinCompile-setClasspath-getClasspath-methods
> Fix build error on using KGP removed method

- atomicfu/build.gradle
Related YT issue: https://youtrack.jetbrains.com/issue/KT-53748/Remove-KotlinCompile-setClasspath-getClasspath-methods
Related PR in `kotlin-community/dev`: https://github.com/Kotlin/kotlinx-atomicfu/pull/297
> Fix build error on using KGP removed method (#297)

- README.md
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/internal/Assert.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/JvmProjectTest.kt
- atomicfu-gradle-plugin/src/test/kotlin/kotlinx/atomicfu/plugin/gradle/test/MppProjectTest.kt
- atomicfu-gradle-plugin/src/test/resources/projects/jvm-simple/jvm-simple.gradle.kts
After update from Gradle 6.8 to 7.3 the problem with building jvm-only projects was found: jar task is failing with this error
```
Execution failed for task ':jar'.
> Entry IntArithmetic.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```
Reproduced with Kotlin 1.8.20+
Jar task tries to pack both original and transformed class files.
Fixes #301, #295
> Duplicated class files in jar

- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
This commit replaces deprecated native atomics from `kotlin.native.concurrent` package with new atomics from `kotlin.concurrent`, because deprecation levels of native atomics will be updated for 1.9.20 in this MR (https://jetbrains.team/p/kt/reviews/10650/timeline), see KT-58123. These changes are required in `kotlin-community/dev` branch for the aggregate build to pass.
NOTE: this commit is not present in develop branch, because new `kotlin.concurrent` atomics are only available since Kotlin 1.9.0. IT SHOULD BE REMOVED after kotlinx.atomicfu updates Kotlin version to 1.9.0 (#313)
> Update native atomics implementation

- build.gradle
- gradle.properties
- gradle/node-js.gradle
There was a breaking change introduced in Gradle 6.8, that caused atomicfu:nodeSetup task to fail with unresolved layout() method. This commit replaces `com.moowork.gradle:gradle-node-plugin` with `com.github.node-gradle:gradle-node-plugin`
> Updated gradle-node-plugin to be compatible with Gradle 7

- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- gradle/compile-options.gradle
The commit from #314 was reverted after merge, because it caused the aggregate build to fail (apiVersion = 1.9 was required to use new native atomics, but it was 1.4 in the project), thus I've commited the apiVersion update to the same branch and reopened the PR.
This is the [test aggregate build](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_kotlinxAtomicfu/322865301?hideProblemsFromDependencies=false&hideTestsFromDependencies=false) that checks atomicfu part of the aggregate build against the current branch before merge to `kotlin-community/dev`.
This problem could be revealed before merge if `kotlin-community/dev` branch relied on the existing Kotlin version, rather then dev versions that may be already removed, I've filed the issue for that: #315.
P.S. This …
> [Reopened PR #314] Update native atomic deprecations

- atomicfu-gradle-plugin/build.gradle
- atomicfu/build.gradle
- buildSrc/src/main/kotlin/KotlinVersion.kt
Native targets `iosArm32` and `watchosX86` are deprecated in 1.9.0.
This commit removes them conditionally in case Kotlin version  >= 1.9.0.
This is necessary for the kotlin-community/* train branches that use Kotlin 1.9.* versions in builds.
> Conditionally remove targets that are deprecated after 1.9.0.

- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/MetadataTransformer.kt
- gradle.properties
`kotlinx.metadata` version update is required to fix the problem with K2 build of ktor: https://youtrack.jetbrains.com/issue/KT-60444/transformJvmMainAtomicfu-fails-with-java.lang.NoSuchMethodError-kotlin.Metadata
> Update kotlinx.metadata to 0.7.0

- atomicfu/src/nativeTest/kotlin/kotlinx/atomicfu/locks/SynchronizedTest.kt
Atomics from kotlin.native.concurrent package are deprecated with error since 1.9.20
See KT-58123
> Use kotlin.concurrent.AtomicInt in SynchronizedTest

- integration-testing/build.gradle
Api used in MavenPublicationMetaInfValidator requires JDK10+
> Upgrade JDK target version to 11 in integration tests.

- gradle/publishing.gradle
- integration-testing/build.gradle
This issue was revealed after enabling integration testing of atomicfu. Now the first TC build step executes `build` and `publishToMavenLocal` tasks. `publishToMavenLocal` task fails with an error: 
```
Reason: Task ':atomicfu:compileTestKotlinLinuxX64' uses this output of task ':atomicfu:signLinuxX64Publication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
This is an already known problem [KT-61313](https://youtrack.jetbrains.com/issue/KT-61313) caused by the task configuration performed by KGP.
This fix is necessary to be able to launch integration tests added in this PR: #344
> Sign publication failure again

- atomicfu/build.gradle
This commit fixes the WA for the failure of clean task on Windows (KT-58303), properly excluding the directory for the Delete task.
> Fix the WA for the failing clean task on Windows

- README.md
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/checker/ArtifactChecker.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/checker/DependenciesChecker.kt
Support of the `enableNativeIrTransformation` flag that enables Native Ir Transformation by the compiler plugin.
> Flag for Native IR integration tests

- build.gradle
The change is related to building kotlinx-atomicfu as a Kotlin user project.
See [QA-1106](https://youtrack.jetbrains.com/issue/QA-1106) for more details.
> Enable error loglevel for partial linkage messages

- integration-testing/examples/jvm-sample/build.gradle.kts
- integration-testing/examples/mpp-sample/build.gradle.kts
Sample projects in integration tests are built with the fixed Kotlin version, that does not depend on the Kotlin version in global gradle.properties. 
Hence in aggregate build we can get an error `Pre-release classes were found in dependencies.`.
> Skip prelease check in sample projects

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- integration-testing/examples/mpp-sample/src/commonMain/kotlin/AtomicSampleClass.kt
- integration-testing/examples/mpp-sample/src/commonTest/kotlin/AtomicSampleTest.kt
- integration-testing/examples/user-project/build.gradle.kts
- integration-testing/examples/user-project/gradle.properties
- integration-testing/examples/user-project/settings.gradle.kts
- integration-testing/examples/user-project/src/commonMain/kotlin/Sample.kt
- integration-testing/examples/user-project/src/commonTest/kotlin/SampleTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/UserProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/BuildRunner.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Commands.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Environment.kt
Fixes #379
Can be tested by building integration tests in kotlinx.coroutines (https://github.com/Kotlin/kotlinx.coroutines/pull/3974).
> Always add a transitive atomicfu dependency for native targets.

- integration-testing/examples/mpp-sample/build.gradle.kts
- integration-testing/examples/user-project/build.gradle.kts
the wrong type of `KotlinCompile` task was provided.
See the original PR: #381.
> Fix adding -Xskip-prerelease-check to integration tests

- integration-testing/build.gradle.kts
`mavenTest` is supposed to check contents of `atomicfu-jvm.jar`. For that it depended on the snapshot version of atomicfu, that should've been published locally. This snapshot dependency broke community-plugin build (see https://youtrack.jetbrains.com/issue/QA-1164/Atomicfu-integration-tests-fail-with-the-community-plugin), because resolution of the snapshot version happened before the artefact was published. 
Replacement of snapshot dependency with `project(":atomicfu")` seems to solve the problem. According to the Gradle [docs](https://docs.gradle.org/current/userguide/declaring_dependencies_between_subprojects.html), `project()` should provide dependency to the artefact produced by the atomicfu project.
Fixes QA-1164
> Fix mavenTest dependency: removed direct dependency to the snapshot version

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- integration-testing/examples/jvm-sample/build.gradle.kts
- integration-testing/examples/jvm-sample/src/main/java/JavaClass.java
In #303 we introduced new directories: `atomicfu-orig` for original sources and `atomicfu` for transformed sources. Though only transformed Kotlin sources were placed into the `atomicfu` directory, that caused a runtime error for projects with Java sources.
In this PR I copy both Kotlin and Java sources to the transformed directory.
In the previous [commit](https://github.com/Kotlin/kotlinx-atomicfu/commit/6c7ca4b03d465f9f2ac399e9f11ef4b6a312f1d0), that was supposed to fix this error, I only added Java sources to the transformed directory.
Fixes #388
> Add all sources to the transformed directory

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
The warning about `compileOnly` dependencies declared for native sourceSets will be specified in 2.0 and will only be triggered when dependency is not present in the `apiElements` config of the native sourceSet. See [KT-64109](https://youtrack.jetbrains.com/issue/KT-64109) for more details.
The corresponding issue: #376
> Add atomicfu to the apiElements config for native targets

- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Utils.kt
`kotlinx.atomicfu` builds were temporary removed from Kotlin Dev (from the aggregate build). 
The reason: atomicfu tests left a Gradle daemon running on an agent after the build was finished. 
Here is the YT ticket: https://youtrack.jetbrains.com/issue/KTI-1608/Project-kotlinx.atomicfu-tests-leak-the-Gradle-daemon-process-used-for-testing
This is how I locally reproduced the problem:
1. killed all Gradle daemons
2. ran integration tests with a `--no-daemon` option
3. saw a Gradle Daemon in jps after the tests completed their execution
Probably, running them with `--no-daemon` will help.
Another solution: I could also check the child processes of the process created with `ProcessBuilder`, and then kill the specified Gradle daemon, but I'm not sure if we need to.
> Run Gradle builds of integration tests with --no-daemon option

- atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/locks/Synchronized.common.kt
- atomicfu/src/commonTest/kotlin/bytecode_test/ReentrantLockTest.kt
- integration-testing/examples/mpp-sample/src/commonMain/kotlin/AtomicSampleClass.kt
- integration-testing/examples/mpp-sample/src/commonTest/kotlin/AtomicSampleTest.kt
- integration-testing/examples/user-project/src/commonMain/kotlin/Sample.kt
Fixes #401
`ReentrantLock` constructor is a public API, though it was not covered with tests and it's direct invocation caused an error `"Expected class has no default constructor"`.
> ReentrantLock expect class should declare a default constructor

- atomicfu/src/nativeInterop/cinterop/interop.def
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/PosixLockSupport.kt
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
This is a prerequisite for #412 to simplify further development and maintenance
The current state:
* No semantic changes
* All interop-related code confined to a dedicated class
* Trivial attempt to get rid of cinterop failed, I've left a few pointers (or can I say `CPointer`s?)
Further step:
* Merge this PR to base branch (`optimize-synchronized`)
* Confine/deprecate excessive public API
* Optimize and fix #412
> Tidy up our synchronization code

- atomicfu-gradle-plugin/build.gradle
- atomicfu-maven-plugin/build.gradle
- atomicfu-transformer/build.gradle
- atomicfu/build.gradle
- atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- build.gradle
- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/KotlinConfiguration.kt
- gradle.properties
- gradle/libs.versions.toml
- gradle/node-js.gradle
- gradle/publish-npm-js.gradle
- integration-testing/build.gradle.kts
- settings.gradle
- settings.gradle.kts
In this PR we moved all the dependencies version in [libs.versions.toml](https://docs.gradle.org/8.4/userguide/platforms.html#sub:conventional-dependencies-toml). Such approach have several advantages:
- Gradle generates type-safe accessors for each dependency
- versions catalog is visible for all projects, so it is a single place to declare all versions
> Moved all the dependencies version to version catalog

- integration-testing/build.gradle.kts
- integration-testing/examples/mpp-sample/build.gradle.kts
- integration-testing/examples/mpp-version-catalog/settings.gradle.kts
- integration-testing/examples/mpp-version-catalog/shared/build.gradle.kts
- integration-testing/examples/plugin-order-bug/build.gradle
- integration-testing/examples/user-project/build.gradle.kts
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppVersionCatalogTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MultiModuleTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/PluginOrderBugTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/UserProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/checker/ArtifactChecker.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/BuildRunner.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/BuildScriptConfigurator.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Commands.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Environment.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Utils.kt
Fixes #419
The main goal of this PR is to test builds of projects from `integration-testing` against the Kotlin version used to build the library. E.g. in Aggregate build test projects should be built with Kotlin from master branch. Otherwise with the same Kotlin version that is set in the root `gradle.properties` file.
Previously Kotlin version for all integration tests was hardcoded in their local `gradle.properties` files.
> Run integration tests with Kotlin version used to build the library

- integration-testing/build.gradle.kts
Updated integration test configurations according to [gradle docs](https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests).
It helps to IJ IDEA better resolve test source and run tests using IJ IDEA gutters
> Extended integration tests configurations with implementation conf

- .gitignore
- atomicfu-gradle-plugin/build.gradle.kts
- atomicfu-gradle-plugin/src/main/resources/META-INF/gradle-plugins/kotlinx-atomicfu.properties
- atomicfu-maven-plugin/build.gradle.kts
- atomicfu-transformer/build.gradle.kts
- buildSrc/src/main/kotlin/base-publish-conventions.gradle.kts
- buildSrc/src/main/kotlin/kotlin-jvm-conventions.gradle.kts
- buildSrc/src/main/kotlin/kotlin-jvm-publish-conventions.gradle.kts
- buildSrc/src/main/kotlin/kotlin-multiplatform-publish-conventions.gradle.kts
- buildSrc/src/main/kotlin/publish-with-javadoc-conventions.gradle.kts
- gradle/libs.versions.toml
- integration-testing/build.gradle.kts
- integration-testing/examples/jdk-compatibility/build.gradle.kts
- integration-testing/examples/jvm-sample/build.gradle.kts
- integration-testing/examples/mpp-sample/build.gradle.kts
- integration-testing/examples/mpp-version-catalog/shared/build.gradle.kts
- integration-testing/examples/multi-module-test/producer/build.gradle.kts
> Apply kotlinx-atomicfu plugin by id

- README.md
- atomicfu-gradle-plugin/build.gradle.kts
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicfuKotlinCompilerPluginInternal.kt
- integration-testing/examples/jdk-compatibility/build.gradle.kts
- integration-testing/examples/jvm-sample/build.gradle.kts
- integration-testing/examples/mpp-sample/build.gradle.kts
- integration-testing/examples/mpp-version-catalog/shared/build.gradle.kts
- integration-testing/examples/multi-module-test/producer/build.gradle.kts
- integration-testing/examples/plugin-order-bug/build.gradle
To be published on GPP the gradle plugin should be namespaced and the plugin cannot be published with the old id `kotlinx-atomicfu` as it was before. So, the plugin name is changed to `org.jetbrains.kotlinx.atomicfu`. 
And here is how the plugin should be applied now: 
```
plugins {
id("org.jetbrains.kotlinx.atomicfu") version "0.25.0"
}
```
> Fix the new ID of the atomicfu-gradle-plugin

- build-settings-logic/src/main/kotlin/atomicfu-dependency-resolution-management.settings.gradle.kts
- buildSrc/settings.gradle.kts
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Utils.kt
- settings.gradle.kts
This PR adds common settings plugin to: 
- root `settings.gradle.kts` 
- buildSrc `settings.gradle.kts` 
It removes duplicated logic by setting custom Kotlin version and custom repository URL. (`kotlin_version`, `kotlin_repo_url`, `build_snapshot_train`).
Should be checked after https://github.com/Kotlin/kotlinx-atomicfu/pull/453.
> De-duplicated the version override in the actual project and in buildSrc

- integration-testing/examples/multi-module-test/build.gradle.kts
- integration-testing/examples/multi-module-test/consumer/build.gradle.kts
- integration-testing/examples/multi-module-test/producer/build.gradle.kts
Test project was applying Kotlin KMP plugin in subprojects, but not in the root 'build.gradle.kts' which is wrong from KMP point of view as it introduces Gradle classpath isolation problem.
> Fix wrong test setup

- gradle/libs.versions.toml
ASM 9.7 supports Java 23 bytecode.
This is needed in order to support JVM target bytecode version 23 in Kotlin compiler (KT-71537), because there's an integration test at `integration-testing/examples/jdk-compatibility` which uses ASM with the latest supported JvmTarget version.
> Update ASM to 9.7

- atomicfu-gradle-plugin/build.gradle.kts
- atomicfu-gradle-plugin/gradle.properties
- atomicfu-transformer/api/atomicfu-transformer.api
- atomicfu-transformer/build.gradle.kts
- atomicfu-transformer/gradle.properties
- atomicfu/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/gradle-compatibility.gradle.kts
- gradle/libs.versions.toml
This also changes LV/AV of :atomicfu-transformer as it is as a runtime dependency of the plugin and contributes to compatibility with Gradle. In future, it's preferred to get rid of the dependency and use it through isolated classpath and Gradle Workers API. 
Relates to KT-60521
> Run Gradle plugin compilation via fixated Kotlin compiler version

- atomicfu/build.gradle.kts
Upcoming changes in Kotlin Gradle Plugin introduce JavaCompile tasks to the KMP/JVM target. This will lead to JVM target validation error when Kotlin JVM compile task will have different JVM target from JavaCompile task.
To avoid this - switched configuring JVM target to the JVM toolchain configuration, which also configures JavaCompile tasks.
> Fix jvm target validation error

- atomicfu/build.gradle.kts
- buildSrc/src/main/kotlin/JdkToolchain.kt
Previous commit configured JDK toolchain 1.8 which also has configured the same JDK for custom JavaExec and Test tasks. Apparently, they expect to be run on JDK 9+, otherwise they are failing with missing symbols error.
Validated the build is passing by running `check` task.
> Fix test tasks jdk

- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/AtomicFUTransformer.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/FlowAnalyzer.kt
- atomicfu-transformer/src/main/kotlin/kotlinx/atomicfu/transformer/MetadataTransformer.kt
- atomicfu/build.gradle.kts
- build-settings-logic/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/gradle-compatibility.gradle.kts
- buildSrc/src/main/kotlin/kotlin-base-conventions.gradle.kts
- gradle.properties
I've enabled warning-as-errors mode in build scripts and Gradle plugin compilation to avoid usages of deprecated methods.
> Build warnings as errors

- atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/NativeMutexNode.kt
- atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
- Move NativeMutexNode to a separate file 
- Rename enter/exit to lock/unlock
> Better align the apple implementation with other native platforms

- atomicfu/build.gradle.kts
Relates to KT-68597, KT-75144
A PR to `develop` fixing this will be created later after migration to 2.1.20
> Suppress K/JS configuration deprecation warnings

- atomicfu/build.gradle.kts
This symbol is deprecated in Kotlin 2.1.20 with warning level and raised to error in 2.2.0. To be migrated to the new API after updating Kotlin to 2.1.20
Relates to KT-68597, KT-75144
> Suppress K/JS configuration deprecation warnings in buildscript

- buildSrc/src/main/kotlin/base-publish-conventions.gradle.kts
This replaces the custom name with an SPDX identifier to enable tooling to automatically detect the correct license. Using an SPDX identifier is recommended [by the official Maven documentation](https://maven.apache.org/pom.html#Licenses).
See https://spdx.org/licenses/Apache-2.0.html
> Use SPDX identifier in POMs

- integration-testing/examples/mpp-version-catalog/shared/build.gradle.kts
Missed it in the previous commit.
> Additional fix for kotlinOptions deprecation error issue in tests

- integration-testing/examples/mpp-sample/gradle.properties
- integration-testing/examples/mpp-version-catalog/gradle.properties
- integration-testing/examples/plugin-order-bug/gradle.properties
- integration-testing/examples/user-project/gradle.properties
Follow up for #540.
See KT-78372.
> Disable cross-compilation for integrational tests

- integration-testing/build.gradle.kts
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/JvmProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppProjectTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MppVersionCatalogTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/MultiModuleTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/cases/PluginOrderBugTest.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/checker/DependenciesChecker.kt
- integration-testing/src/functionalTest/kotlin/kotlinx.atomicfu.gradle.plugin.test/framework/runner/Commands.kt
Speedup integration tests execution by:
- abstaining from running redundant commands;
- combining multiple commands into a single Gradle invocation, where possible;
- enable parallel tests suite execution;
- split the slowest suite (`MppProjectTest`) into a several suite to exploit parallel suite execution.
As a result, on Windows (which is the slowest platform w.r.t. tests execution), execution times improves by 15 minutes.
> Speedup integration tests

- atomicfu-gradle-plugin/build.gradle.kts
Enabling stricter validation means problems with configuration of the Gradle plugin can be caught earlier.
Unfortunately it's not enabled by default yet https://github.com/gradle/gradle/issues/22600
> Enable stricter Gradle plugin validation

- atomicfu-gradle-plugin/api/atomicfu-gradle-plugin.api
- atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt
Gradle tasks should be subtypes of DefaultTask, not the internal `ConventionTask`
> Remove usage of internal Gradle API

- buildSrc/src/main/kotlin/KotlinConfiguration.kt
It was decided to deprecate and phase out the concept (see KT-77721).
> [KUP] Disable opt-in Kotlin compiler warnings
